


services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: theatre_test
      MYSQL_USER: theatre
      MYSQL_PASSWORD: theatre
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3318:3306"
    volumes:
      - database_test_data:/var/lib/mysql
    
  adminer:
    image: adminer
    ports:
      - "8082:8080"
volumes:
  database_test_data:
